### ISSUE TITLE
Build the shopping page front-end

### ISSUE THREAD

**Issue by Rokkema** [IlyaSulli/SSH-SharedCart#15]

**Comment by IlyaSulli** [comment]
Your shopping page has a few minor issues, 
- The cart spacing between the theme button is too close
- The search box filled text is black but it should have the `--defaultdarktextcolor` property
- The search box feels a bit too big, as well as the search box. Maybe copy the css for the container from the cart

Other than those visual issues, everything looks good 😄

**Comment by Rokkema** [comment]
I've updated the design, barring any structural issues I'll close this issue now.
