### ISSUE TITLE
Design the framework for the frontend

### ISSUE THREAD

**Issue by IlyaSulli** [IlyaSulli/SSH-SharedCart#2]

**Comment by IlyaSulli** [comment]
This is the first look at the design concept
![Cart](https://github.com/user-attachments/assets/c43401a4-b556-4330-918d-ae8e243a7431)
![Searching](https://github.com/user-attachments/assets/7348caa9-cce5-4090-a8d7-8c3f09747511)
![Searching-1](https://github.com/user-attachments/assets/345df5ee-7fbc-4f1d-a090-0a997debab7e)

**Comment by Hector-Warner** [comment]
This looks really good!
