### ISSUE TITLE
Back End for basket page

### ISSUE THREAD

**Issue by cdmacc** [IlyaSulli/SSH-SharedCart#4]
Make the Java code for the basket page so it produces all the correct information (lists of each item ordered (with info such as name/price and who ordered it), total price, delivery fee ect) that can then be displayed by the front end basket page

**Comment by IlyaSulli** [comment]
Based on the cart page, the server will need the functions:
- Request an update for an item quantity for a user
     - **Client**: Sends request to the server with (item id, new quantity) - the session token of the signed in user infers their user id
     - **Server**: Sends response based off of the request (was it successful) and the new quantity
- Request removal of an item
    - **Client**: Sends request to the server with (item id) - the session token of the signed in user infers their user id
    - **Server**: Sends response based off of the request (was it successful)
- Update the confirm status for the order for a user
    - **Client**: Sends the request to the server with (boolean confirm status) - the session token of the signed in user infers their user id
    - **Server**: Sends response based off of the request (was it successful) and the new status
- Send the list of items in the cart
    - **Client**: Sends a request to the server (none)
    - **Server**: Sends a response based off of the request (was it successful) and a query result as a json file as the following output example:
```json
{
    "2":{ 
        "name":"John Davis"
        "cart":[
            "15": {
                "name": "Potatoes"
                "description": "Lorem ipsum"
                "image_link": "https://example.com/image.png"
                "price": 1.79
                "quantity": 2
            }
            "27": {
                "name": "Carrots"
                "description": "Lorem ipsum 2"
                "image_link": "https://example.com/image2.png"
                "price": 2.50
                "quantity": 1
            }
        ]
    }
}
```
- Send the list of shops
    - **Client**: Sends a request to the server (none)
    - **Server**: Sends a response based off of the request (was it successful) and a query result as a json file as the following output example:

```json
{
    "0": {
       "name": "Tesco"
       "delivery_price": 5.99
       "logo": "https://example.com/logo.png"
       "color": "ffffff"
    }
    "1": {
       "name": "Sainsburys"
       "delivery_price": 8.99
       "logo": "https://example.com/logo2.png"
       "color": "000000"
    }
}
```

- Send the selected id
    - **Client**: Sends a request to the server (none)
    - **Server**: Sends a response based off of the request (was it successful) and the query result as the shop id number, send `null` if none is selected
- Update the selected id
    - **Client**: Sends a request to the server with the new shop id
    - **Server**: Sends a response based off of the request (was it successful) and the updated shop id

---
Please let me know if anything is wrong or needs adjusting 😄

**Comment by IlyaSulli** [comment]
An additional field will be needed in the database for the confirmation status, in the form:
```json
{
    "2":{
        "name":"John Davis"
        "confirmed": True
        "cart":[]
     }
}
```

**Comment by Hector-Warner** [comment]
Written a Node.js file and integegrated it with a mongodb database that implements the following APIs:

- **Updating Quantity** (Inputs data from server and updates quantity within the database)
- **Delete Item** (Deletes specific item for a specific user from the database)
- **Update Status** (Checks the confirmed order status in database and sets it to the opposite value (True -> False, False -> True)
- **Get List of Items** (Sends data to JSON file, containing each person who has items, their name, whether they've confirmed order and their total cart)

These APIs are executed when a specific code is written within the url after "?" e.g. localhost:8000/api?getListOfItems

**Comment by IlyaSulli** [comment]
Looking good, just needs some modifications to include a function which can grab the selected shop
