### ISSUE TITLE
Back end for search page

### ISSUE THREAD

**Issue by cdmacc** [IlyaSulli/SSH-SharedCart#7]
Create a search page that when given a search term can produce all the items that contain that search term in a list with all their information back to the front end of all their information.

**Comment by IlyaSulli** [comment]
The following functions will be needed for the search function:
- Send a list of items
    - **Client**: Sends the request to the server with (query, page number)
    - **Server**: Sends a response based off of the request (was it successful) and sends the 10 items related
- Send the selected shop id
    - **Client**: Sends a request to the server (none)
    - **Server**: Sends a response based off of the request (was it successful) and the query result as the shop id number, send `null` if none is selected
- Update the selected shop id
    - **Client**: Sends a request to the server with the new shop id
    - **Server**: Sends a response based off of the request (was it successful) and the updated shop id
- Get the list of people
    - **Client**: Sends a request to the server (none)
    - **Server**: Sends a response based off of the request (was it successful) and the list of users names and their ids as a json file
```json
{
    "0"{
        "name": "John Davis"
    }
    "1"{
       "name": "Casey Lee"
    }
}
```
- Sign in as user
    - **Client**: Sends a request to the server (user id)
    - **Server**: Sends a response based off of the request (was it successful) and the session cookie

- Send the list of shops
    - **Client**: Sends a request to the server (none)
    - **Server**: Sends a response based off of the request (was it successful) and a query result as a json file as the following output example:

```json
{
    "0": {
       "name": "Tesco"
       "delivery_price": 5.99
       "logo": "https://example.com/logo.png"
       "color": "ffffff"
    }
    "1": {
       "name": "Sainsburys"
       "delivery_price": 8.99
       "logo": "https://example.com/logo2.png"
       "color": "000000"
    }
}
```

- Add a new item to the list
    - **Client**: Sends a request to the server (item id, quantity) - the session token of the signed in user infers their user id
    - **Server**: Sends a response based off of the request (was it successful)

---
Please let me know if anything is wrong or needs adjusting 😄
